### ISSUE TITLE
Gateway immediately restarts if it becomes unready

### ISSUE THREAD

**Issue by kevin-lindsay-1** [openfaas/faas-netes#1012]
If you start hitting the gateway with a load that causes it to become unready, it restarts the gateway, instead of routing traffic away.

## Expected Behaviour

The gateway should become unready when it becomes too busy to handle additional requests, lessening the load, and allowing it to become ready again. Becoming unready allows k8s to route service traffic to other endpoints which have pods that are ready. Load balancing.

## Current Behaviour

The gateway restarts the moment it becomes unready because the settings for `liveness` and `readiness` are the same.

```yaml
# pod
...
name: gateway
livenessProbe: # restart the pod when this happens
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
readinessProbe: # route traffic away from the pod when this happens
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
```

This means that the gateway is restarted the moment it becomes unready, after 30 seconds of continuous activity. I currently believe this to be the reason for the crashloop when the gateway restarts, because it seems to be getting requests before it's done initializing (likely due to not having a delay period on the probes), which causes it to fail to connect to dependent services, causing an `err` which causes a crash, which is reasonable during a boot, because you don't expect load during a boot.

The gateway receives too many requests, effectively becomes unready, but because none are routed away from it because it is still ready in k8s, it takes on even more requests. This eventually subsides, but if the load doesn't go away after 30s, the pod becomes unready and unhealthy at the same time, unreadiness should take some of the load off, but the unhealthiness causes a restart at the same time, which makes the load greater, because now some requests that would have completed successfully have to be retried.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [x] Yes
- [ ] No

## List All Possible Solutions and Workarounds

livenessProbe and readinessProbe are not supposed to be the same, because if they're the same you effectively have readiness "turned off". why k8s seems to default these probes to the same values is out of scope of OF, but probably default to the same values due to using the same underlying struct.

they should be made different, such as:

```yaml
# pod
...
name: app
livenessProbe:
  failureThreshold: 12
  initialDelaySeconds: 10 # during pod creation, wait before checking this
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
# this is a very sensitive readiness probe, but since the check isn't that expensive, it may be preferable
# because other gateway pods should be able to handle the requests
readinessProbe:
  failureThreshold: 1
  initialDelaySeconds: 10 # during pod creation, wait before checking this
  periodSeconds: 1
  successThreshold: 1
  timeoutSeconds: 1
```

With the assumption that both liveness and readiness are using the same endpoint (`/health` or equivalent), this effectively reads as "if the health check endpoint fails once, the pod is too busy, and requests should not be routed to it. if the pod does not become ready within 120 seconds, restart the pod". I have been using these values for quite some time and I have effectively never had a pod restart unintentionally due to HTTP requests/resources becoming overloaded.

If you were to use these settings, if the gateway becomes very busy for a short period of time, k8s routes future requests away from it. If there is no other pod to route to, IIRC k8s gives a 502. My job would backoff on the 502, rather than hammer the gateway more than it can handle. The gateway would then presumably cease to be busy, it would pass its readiness check, and new requests would be routed to it again. This would happen in a loop until the burst is over.

## Which Solution Do You Recommend?

The liveness and readiness probes should:
1. be different
2. have reasonable default values in the chart
3. be able to be manually overridden for fine tuning

## Steps to Reproduce (for bugs)

This is a YMMV issue, because resources are per host node. They gateway will be easier to overload on weaker machines. The only way to really know if the gateway pods on your machine are being overloaded is if readiness were to be more sensitive.

In order to have this issue occur right now, you need to hit a single gateway pod with enough traffic that its health checks fail for a solid 30 seconds. I cannot give a recommendation for the amount of traffic to provide, because it depends on your host node(s). Best I can give is "a lot", which depends on your compute resources.

The easier way to verify this would be to increase sensitivity on both liveness and readiness checks, allowing the person doing troubleshooting to get much more rapid feedback in order to see the behavior. The current readiness checks are very insensitive, and make it very difficult to see when the gateway is overloaded. The amount of traffic needed to reproduce this would likely generate so many logs that it would be difficult to read them.

## Context

During bursts >30s, this causes unexpected restarts and produces behavior that is difficult to have expectations for, because service readiness and availability can produce any number effects in downstream systems.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
latest

* Docker version `docker version` (e.g. Docker 17.0.05 ):
latest stable

* What version and distriubtion of Kubernetes are you using? `kubectl version`
latest stable

* Operating System and version (e.g. Linux, Windows, MacOS):
linux

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
Hi Kevin,

How can we reproduce this? We need more details to be able to help here. 

Alex

**Comment by kevin-lindsay-1** [comment]
I'm editing this issue since the breakout from related issue. It will provide reasoning and reproducibility.

**Comment by kevin-lindsay-1** [comment]
I should be done editing the original comment now. I can't think of anything else to really add to it at this point.

**Comment by alexellis** [comment]
Would you like to send a PR for the Helm chart to add these entries to the gateway-dep.yaml file and values.yaml?

I think it would look something like:

```yaml
gateway:
  liveness:
    periodSeconds: 10s
  readiness:
    periodSeconds: 10s
```
