### ISSUE TITLE
How can I integrate cAdvisor with the Prometheus pod deployed by OpenFaaS? 

### ISSUE THREAD

**Issue by baddogpack** [openfaas/faas-netes#1030]
I have been trying for a few days to expose cAdvisor metrics on prometheus with no luck. Help in the right direction would be greatly appreciated.

## Expected Behaviour

I would like for Prometheus to scrape the pods performance output by cAdvisor.

## Current Behaviour

Currently cAdvisor metric scraping by Prometheus is not supported by OpenFaaS out of the box.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ + ] No

## List All Possible Solutions and Workarounds

Using https://github.com/prometheus-operator/kube-prometheus I was able to get the cAdvisor metrics but this required a separate Prometheus deployment which is not ideal. 

Deploying cAdvisor container and modifying helm chart to add additional prometheus configuration. 
https://github.com/google/cadvisor#:~:text=VERSION%3Dv0.36.0%20%23%20use,cadvisor/cadvisor%3A%24VERSION
https://github.com/baddogpack/faas-netes/blob/master/chart/openfaas/values.yaml#:~:text=%23%20monitoring%20and,annotations%3A%20%7B%7D'

Other random stuff

## Which Solution Do You Recommend?

I'm just generally confused and am not what steps should be taken to achieve this task. Any nudge in the right direction will help so much. I feel like modifying the Prometheus default deployment defined by OpenFaaS is the correct approach just where and how to make that modification is unclear to me at this time. 

## Context

I am trying to tune a scheduler based on metrics returned from cAdvisor.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.14.8

* Docker version `docker version` (e.g. Docker 17.0.05 ): 20.10.17

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS 12.6

* Link to your project or a code example to reproduce issue: 

* What network driver are you using and what CIDR? i.e. Weave net / Flannel - Unknown

**Comment by alexellis** [comment]
Hi, thanks for your interest in OpenFaaS

We don't provide support via GitHub, but use it to track issues.

That said, before we get this closed, can you explain which metrics you need to collect and why?

Alex

**Comment by baddogpack** [comment]
Thank you for leaving open for now. My apologies I was looking for the correct support channels but I guess discord/slack has moved to the weekly meeting? 

The metrics I'm after are:
  - container_cpu_usage_seconds_total
  - container_spec_cpu_shares
  - container_cpu_cfs_throttled_seconds_total
  - container_memory_working_set_bytes
 
From my understanding these metrics are exposed through cAdvisor.

I'm looking to expose the metrics because the serverless scheduling algorithm developed by colleague relies upon them to make scheduling decisions. https://wwang.github.io/papers/KneeScale.pdf (Unfortunately, the colleague is unavailable to field my questions at this time.)

**Comment by baddogpack** [comment]
Hello,

Today I tried configuring the default prometheus.yml file provided by openfaas https://github.com/openfaas/faasd/blob/master/prometheus.yml (realizing this is for faasd not openfaas, that may have caused some issues) by adding 

`  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets: ['127.0.0.1:8080']`
   
then using a dockerfile I made an image and configured the default Prometheus image used by OpenFaaS with 

`--set prometheus.image=baddoghaus/prometheus:latest`

Still coming up short...

**Comment by alexellis** [comment]
Let's get this issue moved to the right repo then. 

You should also bear in mind that faasd doesn't have any planned support for horizontal scaling. Please read the README for the project and follow the link to the ROADMAP to learn more.

**Comment by baddogpack** [comment]
Great success!

After at least 50 hours of trail an error I finally got it!

Solution:

1. clone: https://github.com/openfaas/faas-netes
2. edit `faas-netes/chart/openfaas/templates/prometheus-cfg.yaml` to include `cAdvisor` in `scrape_configs:` as seen here [https://prometheus.io/docs/guides/cadvisor/#prometheus-configuration](url)

```scrape_configs:```
...
```
- job_name: 'cadvisor'
  scrape_interval: 5s
  static_configs:
    - targets: 
      - cadvisor:8080
```
      
3. deploy with helm instead of arkade
4. deploy a cAdvisor daemonset

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: openfaas
spec:
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
#      nodeSelector:
#        faas_function: float
      containers:
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:v0.45.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: var-run
              mountPath: /var/run/docker.sock
              readOnly: false
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: docker
              mountPath: /var/lib/docker  #Mouting Docker volume
              readOnly: true
            - name: disk
              mountPath: /dev/disk
              readOnly: true
      volumes:
        - name: rootfs
          hostPath:
            path: /rootfs
        - name: var-run
          hostPath:
            path: /var/run/docker.sock
        - name: sys
          hostPath:
            path: /sys
        - name: docker
          hostPath:
            path: /var/lib/docker #Docker path in Host System
        - name: disk
          hostPath:
            path: /dev/disk
```

haha solution vs effort seems off but I learned a lottt!!!

A pretty simple modification for access to a lot of great metrics https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md
