### ISSUE TITLE
[Question] About workflow in high concurrency situation

### ISSUE THREAD

**Issue by lyudmilalala** [openfaas/faas-netes#1089]
I am trying to understand how OpenFaaS (faas-netes specifically) works in a high concurrency situation with multiple synchronous functions. 

I read documentations on github and the official website, and went over [this post and video](https://www.openfaas.com/blog/autoscaling-functions/), but still feel ambiguous about the part of the workflow. **Also, please point out if there is any difference between the implementation of community edition and Pro,** because when I go through the documentations, I often can't tell which edition it refers to.

For example, 
- I have a fixed number, let's say 2, servers to be used as k8s nodes, each server has 8MB memory.
  More specifically, if it would help, servers would be ubuntu 22.04, docker version would be 20.10, k8s version would be 1.23.17.
- I have two **memory-intensive synchronous** functions which will be run on these worker nodes. Function A costs at most 2MB memory per call and function B costs at most 4MB memory per call. To avoid k8s worker node out of memory, I set the request memory in config to ensure only when the node still have larger than 2MB memory, it will create a new pod for function A. (Hope I am correct about this part.) Indeed I would setup a `stack.yml` like the following:
   ```yaml
    version: 1.0
    provider:
    name: openfaas
    gateway: http://127.0.0.1:8080
    functions:
        funcA:
            lang: go
            handler: ./funcA
            image: funcA:latest
            limits:
                memory: 2Mi
            requests:
                memory: 2Mi
        funcB:
            lang: go
            handler: ./funcB
            image: funcB:latest
            limits:
                memory: 4Mi
            requests:
                memory: 4Mi
   ``` 

**Situation 1:** If I have 1000 concurrent requests for function A:
Q1: Will all requests be handled serially? 
Q2: Will the requests be queued? If yes, where did they be queued? 
Q3: If I do not set up a `com.openfaas.scale.max` for function A, will the k8s workers go out of memory?
Q4: Will the logic and workflow be different if the intensive resource is CPU but not memory?

**Situation 2:** If there is no request for function B, my worker nodes can run 8 function A pod in parallel. To fully used all resources, I set `com.openfaas.scale.max` of function A to 8. For the same reason, I set `com.openfaas.scale.max` of function B to 4.
Q5: if I have 3 function A requests and 3 function B requests at the same time, will the last incoming request be queued? Will the worker nodes go out of memory? 

I also have another Question 5 not related to the example above.
Q6: I am trying to implement auto scaling by cpu or memory utilization by myself based on the community edition by myself (just for personal study). When I searched for tutorials, I found there were few useful posts and all of them were pretty long time ago. The support for auto scaling by k8s HPA seems also be deprecated. (Is this true?) As these auto scaling implementations already become part of OpenFaaS Pro, I am wondering is it still acceptable for me to ask questions about them here if I face some problems? Can I ask questions about them on Stackoverflow or some other forums?
