### ISSUE TITLE
Config: Set timeouts via helm-chart [help wanted]

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#132]
We should be able to configure read/write and queue-worker timeouts via the helm chart in the values.yml file. I'd like help with this.

For the gateway/faas-netesd:

```
         env:
        - name: read_timeout
          value: "60"
        - name: write_timeout
          value: "60"
```

For the queue-worker see the existing YAML file which defines a timeout of 30s.
