### ISSUE TITLE
Question: Secrets as environment variables?

### ISSUE THREAD

**Issue by rmb938** [openfaas/faas-netes#153]
## Expected Behaviour
Secrets can be mounted as volumes or used as environment variables

## Current Behaviour
Secrets can only be mounted as volumes

## Possible Solution
One solution would be making the function definition slightly more complex. An example would be

```
functions:
  myfunction:
    image: local/myfunction
    secrets:
      - name: my-secret1
         mount:
            location: /run/secrets/my-secret
      - name: my-secret2
         environment:
            key: my-secret-key
            location: MY_SECRET_2
```

This will mount all keys under `my-secret1` at `/run/secrets/my-secret` and place `my-secret-key` from `my-secret2` into the environment variable `MY_SECRET_2`

This same solution could also apply for configmaps. I do know that Docker Swarm's Secrets and Configs are slightly different and a solution would have to be made that satisfies both runtimes.

## Context

Most cloud native apps use 12factor which recommends storing configuration (and optionally secrets) in environment variables. https://12factor.net/config It would be nice for functions to be able to follow those same standards.

## Your Environment

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Kubernetes
