### ISSUE TITLE
envVars in Swagger docs should be map and not an array

### ISSUE THREAD

**Issue by martin-liu** [openfaas/faas-netes#204]
When I try to call REST API to deploy a function, it always fail if I provide `envVars` parameter.
Then I searched the code and found the implementation is inconsistent with the API doc.

## Expected Behaviour
From [API doc](https://github.com/openfaas/faas/blob/0.8.0/api-docs/swagger.yml#L238), there's parameter `envVars` and it should be an array of string
```yaml
      envVars:
        type: array
        items:
          type: string
        description: Overrides to environmental variables
```

## Current Behaviour
From [Code](https://github.com/openfaas/faas-netes/blob/0.5.2/handlers/deploy.go#L268), it's expecting `request.EnvVars` and it's a `map`
```go
func buildEnvVars(request *requests.CreateFunctionRequest) []v1.EnvVar {
	envVars := []v1.EnvVar{}

	if len(request.EnvProcess) > 0 {
		envVars = append(envVars, v1.EnvVar{
			Name:  "fprocess",
			Value: request.EnvProcess,
		})
	}

	for k, v := range request.EnvVars {
		envVars = append(envVars, v1.EnvVar{
			Name:  k,
			Value: v,
		})
	}

	return envVars
}
```

## Possible Solution
I'm not sure if the API doc is outdated or the code need to fit the doc

## Steps to Reproduce (for bugs)
Call REST API to deploy function with `envVars` parameter

## Your Environment
k8s v1.9.2
