### ISSUE TITLE
Scale label should not be set on pods

### ISSUE THREAD

**Issue by carsonoid** [openfaas/faas-netes#210]
`com.openfaas.scale.min` is used to set the [min scale on a deployment](https://github.com/openfaas/faas-netes/blob/master/handlers/deploy.go#L351). That is great! But the label should be removed from the pod labels list. It doesn't doesn't make sense to actually be applied to the pods and labels in Kubernetes shouldn't be used for data like that in the first place.

## Expected Behaviour

`com.openfaas.scale.min` is read and used to create the deployment at the right scale. But the label should not be applied to the pods.

## Current Behaviour

The label is used for config **and** gets set on the pods.

## Possible Solution

Delete `com.openfaas.scale.min` from the map before referencing it in the pod spec.

## Steps to Reproduce (for bugs)

Sample `function yaml`:

```yaml
functions:
  echolimit:
    lang: dockerfile
    handler: ./echo
    image: functions/faas-echo:latest
    labels:
      com.openfaas.scale.min: "2"
```

## Context

It seems harmless, but pod labels are often read by metric systems and should be kept clean.

To quote https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/:

> We’ll eventually index and reverse-index labels for efficient queries and watches, use them to sort and group in UIs and CLIs, etc. We don’t want to pollute labels with non-identifying, especially large and/or structured, data. Non-identifying information should be recorded using annotations.
