### ISSUE TITLE
Install openFaas on openshift

### ISSUE THREAD

**Issue by vodasan** [openfaas/faas-netes#223]
I try to install openFaas on my openshift instance. 

I follow this:
- https://blog.getupcloud.com/openfaas-openshift-c76658949365.
- https://blog.openshift.com/openfaas-on-openshift/

But when I invoke a function, i have an Internal Server Error. Can't reach service: XXXX

## Expected Behaviour
When I invoke function, I will have the reponse and a 200 HTTP code.

## Current Behaviour
I have an Internal Server Error with this message "Can't reach service: figlet"
However, i see a deployment in openfass-fn.

## Steps to Reproduce (for bugs)
1. Create two openShift project "openfaas", "openfass-fn"
2. Create faas-controller and add policy between the two project.
3. Apply yml files (alertmanager, ....)
4. Expose route
5. Go on the gateway, deploy figlet function
6. Invoke figlet function.

## Context
I use an instance of openshift.

## Your Environment

oc v3.9.27
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://master.xxxxx:443
openshift v3.7.23
kubernetes v1.7.6+a08f5eeb62

**Comment by alexellis** [comment]
I would have though the figlet function is running as root. which OpenShift will not allow to execute.

Maybe you could check the logs of the gateway and faas-netes to see if there was an error at deployment time of figlet? Are you certain that in the UI the Invoke button is showing as enabled and that you're using all the latest components of OpenFaaS and not an old fork from Michael's blog post? i.e. don't use https://github.com/mhausenblas/faas-netes.git

Alternatively, create a new function in Python which uses a non-root user then build it, push it to a registry or the Docker Hub and deploy that instead.

**Comment by vodasan** [comment]
OK. I removed all and I use https://github.com/openfaas/faas-netes.git

Prometheus failed. In logs, i see this 

> err="Opening storage failed mkdir data/: permission denied"

![openfass-prometheus](https://user-images.githubusercontent.com/30429204/41708858-09c20da8-7542-11e8-8a4a-c7c5dc10533c.PNG)

**Comment by alexellis** [comment]
I believe for Prometheus you will need to add an empty_dir - this isn't a fatal error though and you should still be able to deploy a function.

How can I set up OpenShift on Linux? I tried minishift on a Linux VM but got an error saying KVM was not supported.

**Comment by vodasan** [comment]
The prometheus pod crashed but I can deploy a function. I try nodeinfo. I have a gateway time-out.

I don't know how set up OpenShift on Linux. It was done by another.

**Comment by simonpasquier** [comment]
_sorry for highjacking the thread_

> I tried minishift on a Linux VM but got an error saying KVM was not supported.

It should be supported if you follow https://docs.openshift.org/latest/minishift/getting-started/setting-up-virtualization-environment.html#setting-up-kvm-driver

Otherwise [`oc cluster up`](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md) works reasonably well for me on Linux.

**Comment by alexellis** [comment]
@simonpasquier I followed all those instructions but it looks like the provider of the VM (Civo) - doesn't support nested VMs.

@vodasan - it looks like NodeInfo is working correctly from the logs?

You need to set up an empty_dir volume mount for Prometheus.

**Comment by vodasan** [comment]
I have nothing in nodeinfo pod logs.

How set up an empty_dir volume mount?

**Comment by simonpasquier** [comment]
FWIW I've done a quick test to deploy OpenFaaS on my local OpenShift cluster and it's working fine albeit the Prometheus crash that can be fixed by adding an emptyDir volume to the Prometheus deployment.

@vodasan are you sure that all pods are created? I had to wait for the images to be pulled otherwise I also encountered the gateway time-out.

@alexellis then I would definitely recommend `oc cluster up`. Happy to help you on this!

**Comment by simonpasquier** [comment]
@vodasan I've edited the prometheus deployment from the OpenShift console to add the following bits (open the prometheus deployment page and click the "Edit YAML" button in the right-corner menu):

```yaml
        - command:
            - prometheus
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
          # <snip>
          volumeMounts:
            - mountPath: /prometheus
              name: prometheus-data
          # <snip>
      volumes:
        - emptyDir: {}
          name: prometheus-data
```

**Comment by vodasan** [comment]
I update my YAML like this

```
volumes:
        - emptyDir: {}
          name: prometheus-data
        - name: prometheus-config
          configMap:
          ....
```

But pod still crash

**Comment by alexellis** [comment]
You may need to make it writeable too.. 

```
          volumeMounts:
            - mountPath: /prometheus
              name: prometheus-data
              readOnly: false
```
