### ISSUE TITLE
Config: Helm/YAML - check all deployments for livenessProbe/readinessProbe

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#261]
All services that can support it should have a probe for both livenessProbe/readinessProbe

I noticed a mixture in the helm charts, the same should apply for the YAML files

Example:

```
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
```
