### ISSUE TITLE
[helm chart] Support other cluster domains than "cluster.local"

### ISSUE THREAD

**Issue by kirecek** [openfaas/faas-netes#266]
## Expected Behaviour

gateway should be able to connect to nats when deploying to kubernetes cluster with custom domain name.

## Current Behaviour

Gateway use "cluster.local" domain for nats address which does not work with custom domains.

```yaml
value: "nats.{{ .Release.Namespace }}.svc.cluster.local."
```

Pods ends in error state:
```
2018/08/03 07:28:51 Opening connection to nats://nats.default.svc.cluster.local.:4222
2018/08/03 07:28:51 nats: no servers available for connection
```

## Possible Solution

- add  `kubernetesDNSDomain: cluster.local` to `values.yml`

- change **faas_nats_address** and **direct_functions_suffix** env values:

```yaml
        - name: faas_nats_address
          value: "nats.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesDNSDomain }}."
        - name: direct_functions_suffix
          value: "{{ $functionNs }}.svc.{{ .Values.kubernetesDNSDomain }}."
```

## Steps to Reproduce (for bugs)

1. setup custom domain name in kubernetes cluster
2. install openfaas chart
