### ISSUE TITLE
(armhf only) Gateway 404 when not using direct_functions

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#297]
## Expected Behaviour

When `direct_functions` is set to false function invocations pass through faas-netes as a proxy. Right now that seems to be causing a 404 after PATH support was added. This is not an urgent or concerning issue since nobody should be bypassing the `direct_functions` setting.

The solution is to make the armhf configuration files use `direct_functions` and then to look into why the proxying through faas-netes is failing and patch that code for any older users. Whatever issue exists here may exist in faas-swarm and faas-fargate/nomad.

armhf Plain YAML without `direct_functions`:

https://github.com/openfaas/faas-netes/blob/master/yaml_armhf/gateway.yml

```yaml
        env:
        - name: functions_provider_url
          value: "http://127.0.0.1:8081/"
        - name: faas_nats_address
          value: "nats.openfaas"
        - name: faas_nats_port
          value: "4222"
        - name: read_timeout
          value: "60s"
        - name: write_timeout
          value: "60s"
        - name: basic_auth
          value: "false"
```

Plain YAML with `direct_functions`:

https://github.com/openfaas/faas-netes/blob/master/yaml/gateway-dep.yml

```yaml
        env:
        - name: functions_provider_url
          value: "http://127.0.0.1:8081/" # Final `.` specifies an absolute address
        - name: faas_nats_address
          value: "nats.openfaas.svc.cluster.local."
        - name: faas_nats_port
          value: "4222"
        - name: direct_functions
          value: "true"                             # Functions are invoked directly over the overlay network
        - name: direct_functions_suffix
          value: "openfaas-fn.svc.cluster.local."   # contains K8s namespace
        - name: read_timeout
          value: "35s"
        - name: write_timeout
          value: "35s"
        - name: upstream_timeout  # Must be smaller than read/write_timeout
          value: "30s"
        - name: basic_auth
          value: "false"
        - name: secret_mount_path
          value: "/etc/openfaas"
        - name: scale_from_zero
          value: "false"
```

This is unrelated to #293 where helm is being used. Helm does have the setting for `direct_functions` enabled by default: https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/gateway-dep.yaml#L74

Issue reported by Philipp Stuber, I found this while doing a diff on GitHub.
