### ISSUE TITLE
Proposal: Add an example using Traefik or NGinx as an ingress controller.

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#3]
NodePorts are used in the README as a short-cut, but an ingress controller would be better.

**Comment by alexellis** [comment]
Happy to take a contribution for this.

**Comment by mishak87** [comment]
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: faas
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: faas.example.com
    http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: 8080
  - host: faas-prometheus.example.com
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: 9090
  - host: faas-alertmanager.example.com
    http:
      paths:
      - backend:
          serviceName: alertmanager
          servicePort: 9093
```
