### ISSUE TITLE
functions with configmaps

### ISSUE THREAD

**Issue by pyramation** [openfaas/faas-netes#311]
Support (or document) configmaps within openfaas functions

## Expected Behaviour

I should be able to specify both secrets *and* configmaps that reside in the `openfaas-fn` namespace:

```yaml
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  uploader:
    lang: dockerfile
    handler: ./uploader
    image: pyramation/uploader:latest
    environment:
      - name: MINIO_ENDPOINT
        valueFrom:
          configMapKeyRef:
            name: minio-config
            key: MINIO_ENDPOINT
    secrets:
      - dockerhub
      - minio-secrets
```

## Current Behaviour

From the documentation, it looks as though you have to hard-code the `environment` values.

## Possible Solution

Potentially it's already done, or there is a way, and it's not obvious from the docs? 

If if needs implementation, I think it's a best practice to use kubernetes for configmaps and pass env through and let k8s handle it.

## Steps to Reproduce (for bugs)

create a `configmap`

```sh
kubectl create configmap \
    minio-config \
    --namespace openfaas-fn \
    --from-literal=MINIO_HOST=$MINIO_HOST \
    --from-literal=MINIO_PORT=$MINIO_PORT \
    --from-literal=MINIO_ENDPOINT=$MINIO_ENDPOINT 
```

Now add it to your `environment:`

```yaml
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  uploader:
    lang: dockerfile
    handler: ./uploader
    image: pyramation/uploader:latest
    environment:
      - name: MINIO_ENDPOINT
        valueFrom:
          configMapKeyRef:
            name: minio-config
            key: MINIO_ENDPOINT
```

You will see this error when building the function:

```
Error with YAML file
Yaml: unmarshal errors:
  line 11: cannot unmarshal !!seq into map[string]string
```

## Context

I'm trying to use kubernetes best practices.
