### ISSUE TITLE
Support request for kubeadm-dind-cluster with helm

### ISSUE THREAD

**Issue by fadams** [openfaas/faas-netes#393]
Hello, I'm trying out OpenFaaS on kubeadm-dind-cluster https://github.com/kubernetes-sigs/kubeadm-dind-cluster

When I followed the **Deployment guide for Kubernetes** https://docs.openfaas.com/deployment/kubernetes/ for simplicity I first followed the **Deploy using kubectl/YAML**
```
git clone https://github.com/openfaas/faas-netes
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
cd faas-netes && \
kubectl apply -f ./yaml
```
which worked beautifully and gave me a working cluster to play with, and when I open http://10.192.0.2:31112 I see the OpenFaaS Portal and when I open http://10.192.0.2:31119 I see the OpenFaaS Prometheus metrics UI, so all looks good.

As I got a little more ambitious I decided to try deploying via Helm
```
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
helm repo add openfaas https://openfaas.github.io/faas-netes/
helm repo update
   
helm upgrade openfaas --install openfaas/openfaas \
        --namespace openfaas  \
        --set functionNamespace=openfaas-fn
```
In this case however faas-idler and gateway seem to have errors with a big red exclamation mark in the K8s dashboard
```
faas-idler
Back-off restarting failed container

gateway
Back-off restarting failed container
```
In Logs from gateway I'm seeing
```
 2019-03-22T15:35:25.162131249Z 2019/03/22 15:35:25 HTTP Read Timeout: 1m5s
2019-03-22T15:35:25.162227619Z 2019/03/22 15:35:25 HTTP Write Timeout: 1m5s
2019-03-22T15:35:25.162238382Z 2019/03/22 15:35:25 Binding to external function provider: http://127.0.0.1:8081/
2019-03-22T15:35:25.162250711Z 2019/03/22 15:35:25 Async enabled: Using NATS Streaming.
2019-03-22T15:35:25.162328183Z 2019/03/22 15:35:25 Opening connection to nats://nats.openfaas.svc.cluster.local:4222
2019-03-22T15:35:25.162635481Z 2019/03/22 15:35:25 Connect: nats://nats.openfaas.svc.cluster.local:4222
2019-03-22T15:35:27.163390443Z 2019/03/22 15:35:27 nats: no servers available for connection 
```
In order to try and narrow the problem down a little I next tried the instructions for **Deployment with helm template**
```
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
git clone https://github.com/openfaas/faas-netes.git
helm template faas-netes/chart/openfaas \
    --name openfaas \
    --namespace openfaas  \
    --set functionNamespace=openfaas-fn > openfaas.yaml
kubectl apply -f ./openfaas.yaml
```
Now unsurprisingly just doing that gave the same issues as the previous helm attempt as it's generating the same information, but I next decided to check the generated openfaas.yaml and compare it with the gateway-dep.yaml from the original kubectl+yaml install. An interesting thing I noted was that in the gateway-dep.yaml in the env: section I note:
```
        env:
        - name: functions_provider_url
          value: "http://127.0.0.1:8081/" # Final `.` specifies an absolute address
        - name: faas_nats_address
          value: "nats.openfaas.svc.cluster.local."
        - name: faas_nats_port
          value: "4222"
        - name: direct_functions
          value: "true"                             # Functions are invoked directly over the overlay network
        - name: direct_functions_suffix
          value: "openfaas-fn.svc.cluster.local."   # contains K8s namespace
```
however in the openfaas.yaml generated from the Helm chart the equivalent stanza says:
```
        env:
        - name: read_timeout
          value: "65s"
        - name: write_timeout
          value: "65s"
        - name: upstream_timeout
          value: "60s"
        - name: functions_provider_url
          value: "http://127.0.0.1:8081/"
        - name: direct_functions
          value: "true"
        - name: direct_functions_suffix
          value: "openfaas-fn.svc.cluster.local"
        - name: faas_nats_address
          value: "nats.openfaas.svc.cluster.local"
```
That is to say in the one generated from Helm openfaas-fn.svc.cluster.local and nats.openfaas.svc.cluster.local **do not* end with a period whereas in the original gateway-dep.yaml they do.

When I edited the generated openfaas.yaml to include the trailing period and ran
```
kubectl apply -f ./openfaas.yaml
```
The deployment appeared to be set up with no errors appearing on the Kubernetes dashboard.

I believe that there may well be additional issues though because although when I open http://10.192.0.2:31112 I see the OpenFaaS Portal and I appear to be able to navigate to the Function Store and try out a few functions when I open http://10.192.0.2:31119 I **do not** see the OpenFaaS Prometheus metrics UI so something is still not "quite right" with my Helm based deploy.

I'm fairly new to Kubernetes, Helm and OpenFaaS so I'm not really sure if this stuff is due to me using a fairly quirky Kubernetes deployment like kubeadm-dind-cluster (which actually is pretty cool BTW) or whether this is a genuine error in the Helm chart - it does seem suspicious for it to differ in this way from the basic YAML especially given the comment "Final `.` specifies an absolute address".

I'd appreciate any insights that you may have.

MTIA
