### ISSUE TITLE
Make execProbe optional for core services

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#460]
## Expected Behaviour

Core services should check themselves efficiently using httpProbe

## Current Behaviour

They use execProbe so that the chart works with Istio

## Possible Solution

Make a tidy/concise helm template that we can use to let the user pick the most efficient option. 

https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/gateway-dep.yaml#L47

```
        readinessProbe:
          exec:
            command:
            - wget
            - --quiet
            - --tries=1
            - --timeout=5
            - --spider
            - http://localhost:8080/healthz
          timeoutSeconds: 5
```

If set to exec we'd get above, if set to http, we'd get the equivalent http probe.
