### ISSUE TITLE
OpenFaaS not working on a PSP enabled cluster

### ISSUE THREAD

**Issue by stefanprodan** [openfaas/faas-netes#471]
OpenFaaS control plane and functions can't run when [pod security policy](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) is enabled. Tested on EKS 1.13.

## Expected Behaviour
The OpenFaaS installer (chart or yamls) should come with a default pod security policy.

## Current Behaviour
When deploying OpenFaaS no pods will be scheduled:

```
pods "gateway" is forbidden: unable to validate against any pod security policy: []
```

## Possible Solution

* create service accounts for all OpenFaaS control plane workloads
* create a service account for OpenFaaS functions
* create a pod security policy for OpenFaaS control plane and functions
* bind the service accounts to OF PSP

The OF PSP should disable privileged, hostIPC, hostNetwork and hostPID.

Example PSP for OF control plane:
```yaml
{{- if .Values.psp }}
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
    name: {{ .Release.Name }}-psp
    labels:
        app: {{ template "openfaas.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    annotations:
        seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
    privileged: false
    hostIPC: false
    hostNetwork: false
    hostPID: false
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    allowedCapabilities:
        - '*'
    fsGroup:
        rule: RunAsAny
    hostPorts:
        - max: 65535
          min: 1
    runAsUser:
        rule: RunAsAny
    seLinux:
        rule: RunAsAny
    supplementalGroups:
        rule: RunAsAny
    volumes:
        - '*'
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ .Release.Name }}-psp
    labels:
        app: {{ template "openfaas.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
rules:
    - apiGroups: ['extensions']
      resources: ['podsecuritypolicies']
      verbs:     ['use']
      resourceNames:
          - openfaas-psp
---
{{- if .Values.operator.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: {{ .Release.Name }}-psp
    labels:
        app: {{ template "openfaas.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: openfaas-psp
subjects:
    - kind: ServiceAccount
      name: {{ .Release.Name }}-operator
      namespace: {{ .Release.Namespace | quote }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: {{ .Release.Name }}-psp
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ .Release.Name }}-psp
subjects:
    - kind: ServiceAccount
      name: {{ .Release.Name }}-controller
      namespace: {{ .Release.Namespace | quote }}
{{- end }}
{{- end }}
```

## Steps to Reproduce (for bugs)

1. Enable PSP https://kubernetes.io/docs/concepts/policy/pod-security-policy/
2. Deploy OF with yamls
3. Watch the pods fail

## Context

The charts in the official Helm repository are being [patched with PSP](https://github.com/helm/charts/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+psp). 

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
