### ISSUE TITLE
Allow setting key:value pair in secrets api

### ISSUE THREAD

**Issue by lakhansamani** [openfaas/faas-netes#557]
Currently `/system/secrets` API only accepts `name`, `value` in the request body. It would be great if we can support `key: value` pairs. This will help in creating secrets with multiple data values. Also adding `type` param would be really helpful while creating secrets via API.

This will be helpful while deploying private images for functions with secret values. https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

Also, this could be helpful for the function which will need a single secret with multiple key-value pairs.

## Expected Behaviour
It should create k8s secret with specified type and key-value pair.

```
apiVersion: v1
data:
  .dockerconfigjson: dXNlcm5hbWU6cGFzc3dvcmQ=
kind: Secret
metadata:
  name: dockerhub
  namespace: openfaas-fn
type: kubernetes.io/dockerconfigjson
```

## Current Behaviour
Currently, it creates k8s secret with key same as name of the secret

```
apiVersion: v1
data:
  dockerhub: dXNlcm5hbWU6cGFzc3dvcmQ=
kind: Secret
metadata:
  name: dockerhub
  namespace: openfaas-fn
```

## Possible Solution
Add following keys to struct

https://github.com/openfaas/faas-provider/blob/master/types/model.go#L95

```
Data map[string]string{} `json:"data,omitempty"`
Type string `json:"type,omitempty"`
```
Add support for this new params in Create function
https://github.com/openfaas/faas-netes/blob/b14f7275a75ef3e54cb2627d3193296920c88240/k8s/secrets.go#L97

## Context
How has this issue affected you? What are you trying to accomplish?

- Because of this, I was not able to add secret which would help in deploying a private image.

## Your Environment
Using REST Endpoint to create secrets
