### ISSUE TITLE
Scaling from 0 sometimes can yield 502 due to race condition between K8S Pod & K8S SVC

### ISSUE THREAD

**Issue by Templum** [openfaas/faas-netes#589]
Under some circumstances, there is a race condition between the Function Pod being marked as healthy and up vs Function Pod being registered as Endpoint in the SVC Object. 

## Expected Behaviour
As a user, I expect OpenFaaS does only attempts to call my function when it is healthy + up and also is registered as Endpoint in the SVC object.

## Current Behaviour
Under some circumstances, there is race condition going on between Kubernetes API indicating a given POD as healthy + up (Readiness Probe & Health Probe both were successful) and the POD actually beeing registered in the Service Object with an Endpoint. Personally I was only able to observe this during scale from 0 with aggressive Probes, details on how reproducing can be achieved follow below. However, based on the CPU Usage of the K8S cluster this can show up also with more modered probes.

This yields the following behaviour for an (sync) Invocation. OpenFaaS based on K8S API response sees the pods is up an running and forwards the call to it. However as at that time there is technically no endpoint registered, the call will be on hold and eventually timeout once the deadline is exceeded. Kind of similiar behaviour as when you try to access a service object with no pods, where dns resolution works but eventually the request times out with a 502. Here is an example log from the gateway:

```
2020/01/30 14:03:00 GetReplicas [lp-dbb3470f-2b98-4a60-89d6-280e97710a6e.] took: 0.146981s
2020/01/30 14:03:00 GetReplicas [lp-dbb3470f-2b98-4a60-89d6-280e97710a6e.] took: 0.147019s
2020/01/30 14:03:00 GetReplicas [lp-dbb3470f-2b98-4a60-89d6-280e97710a6e.] took: 0.150055s
2020/01/30 14:03:00 GetReplicas [lp-dbb3470f-2b98-4a60-89d6-280e97710a6e.] took: 0.150316s
2020/01/30 14:03:00 GetReplicas [lp-dbb3470f-2b98-4a60-89d6-280e97710a6e.] took: 0.150981s
2020/01/30 14:03:00 GetReplicas [lp-dbb3470f-2b98-4a60-89d6-280e97710a6e.] took: 0.151143s
2020/01/30 14:03:01 GetReplicas [lp-dbb3470f-2b98-4a60-89d6-280e97710a6e.] took: 0.153334s
2020/01/30 14:03:01 GetReplicas [lp-dbb3470f-2b98-4a60-89d6-280e97710a6e.] took: 0.153427s
2020/01/30 14:03:01 GetReplicas [lp-dbb3470f-2b98-4a60-89d6-280e97710a6e.] took: 0.143510s
2020/01/30 14:03:01 GetReplicas [lp-dbb3470f-2b98-4a60-89d6-280e97710a6e.] took: 0.143527s
2020/01/30 14:03:01 [Scale] function=lp-dbb3470f-2b98-4a60-89d6-280e97710a6e 0 => 1 successful - 2.606577 seconds
2020/01/30 14:03:21 Forwarded [GET] to /healthz - [200] - 0.002297 seconds
2020/01/30 14:03:22 Forwarded [GET] to /healthz - [200] - 0.000619 seconds
2020/01/30 14:03:33 error with upstream request to: , Post http://lp-dbb3470f-2b98-4a60-89d6-280e97710a6e.faas:8080?debug=false: dial tcp 10.111.199.126:8080: connect: connection timed out
2020/01/30 14:03:33 Forwarded [POST] to /function/lp-dbb3470f-2b98-4a60-89d6-280e97710a6e?debug=false - [502] - 31.793436 seconds
```

The next call will succeed without any issues. Actually, if the second call was send while the initial scale up from 0 call is still stuck, it will cause the stuck call to be processed successfully.

## Possible Solution
Beside checking for the pod being marked as [healthy + up](https://github.com/openfaas/faas-netes/blob/31b00dff2dd5bc37143ab41af9cee30dd5667388/k8s/function_status.go#L16-L43), also the service object needs to be checked to see if an [endpoint](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#read-endpoints-v1-core) is registered (**Note:** Might be that the linked API is not the correct one to find if a service object has endpoints registered).

## Steps to Reproduce (for bugs)

Sadly the issue is not to easy to reproduce due to the nature of it. I believe CPU load on the Cluster should actually impact it.
I was able to reproduce it on my local mac book, however not frequently. You can use the following steps:

1. Minikube `$ minikube start -p test --kubernetes-version v1.15.6`
2. Deploy OpenFaaS with the the version & conf described under [Your Environment](#Your Environment)
3. Deploy the sample function listed below, base on express10 template.
4. Forward gateway to port 8080 via kubectl `$ kubeclt -n names_space deploy/gateway port-forward 8080:8080`
5. Use the following script to loop scaling + invoking and watch out for a invoking that takes longer.
6. Stop Script + Check gateway logs

```sh
echo "Little script to help with the reproducing. Make sure to port-forward gateway to port 8080"

while true
do
    echo "Scaling to zero"
    kubectl scale -n faas deploy lp-dbb3470f-2b98-4a60-89d6-280e97710a6e --replicas=0
    sleep 5
    echo "Invoking"
    curl -X POST http://localhost:8080/function/lp-dbb3470f-2b98-4a60-89d6-280e97710a6e
    echo ""
    sleep 2
done
```

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    faas_function: lp-dbb3470f-2b98-4a60-89d6-280e97710a6e
  name: lp-dbb3470f-2b98-4a60-89d6-280e97710a6e
  namespace: faas
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      faas_function: lp-dbb3470f-2b98-4a60-89d6-280e97710a6e
  template:
    metadata:
      labels:
        BrandID: le13535243
        BuildedAt: "1580137595911"
        DeployedAt: "1580137598256"
        LambdaUUID: dbb3470f-2b98-4a60-89d6-280e97710a6e
        com.openfaas.scale.max: "5"
        com.openfaas.scale.min: "1"
        faas_function: lp-dbb3470f-2b98-4a60-89d6-280e97710a6e
      name: lp-dbb3470f-2b98-4a60-89d6-280e97710a6e
    spec:
      containers:
      - env:
        - name: LAMBDA_UUID
          value: dbb3470f-2b98-4a60-89d6-280e97710a6e
        - name: NODE_ENV
          value: production
        image: templum/openfaas-node10:express
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/.lock
          initialDelaySeconds: 2
          periodSeconds: 1
          timeoutSeconds: 1
        name: lp-dbb3470f-2b98-4a60-89d6-280e97710a6e
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/.lock
          initialDelaySeconds: 2
          periodSeconds: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 400m
            memory: 256M
          requests:
            cpu: 200m
            memory: 128M
        securityContext:
          readOnlyRootFilesystem: false
```

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): -
* Docker version `docker version` (e.g. Docker 17.0.05 ): `19.03.5`
* What version and distriubtion of Kubernetes are you using? K8S `v1.15.6`
* Operating System and version (e.g. Linux, Windows, MacOS): Minikube (`v1.6.2`) on MacOS  
* OpenFaaS Version & Config
    * openfaas/gateway:0.18.3
    ```
        - name: direct_functions
          value: "true" # Functions are invoked directly over the overlay network
        - name: read_timeout
          value: "15s"
        - name: write_timeout
          value: "40s"
        - name: upstream_timeout  # Must be smaller than read/write_timeout
          value: "35s"
        - name: scale_from_zero
          value: "true"
        - name: max_idle_conns
          value: "1024"
        - name: max_idle_conns_per_host
          value: "1024"
    ```
    * openfaas/faas-netes:0.9.13
    ```
        - name: read_timeout
          value: "15s"
        - name: write_timeout
          value: "35s"
        - name: image_pull_policy
          value: "IfNotPresent"
        - name: http_probe
          value: "false"
        - name: set_nonroot_user
          value: "false"
        - name: readiness_probe_initial_delay_seconds
          value: "2"
        - name: readiness_probe_timeout_seconds
          value: "1"
        - name: readiness_probe_period_seconds
          value: "1"
        - name: liveness_probe_initial_delay_seconds
          value: "2"
        - name: liveness_probe_timeout_seconds
          value: "1"
        - name: liveness_probe_period_seconds
          value: "1"
    ```
