### ISSUE TITLE
Support request for Linkerd2

### ISSUE THREAD

**Issue by tlemarchand** [openfaas/faas-netes#596]
Unless I'm mistaken, it's not possible to provide necessary annotations for Linkerd2 in OpenFaaS Helm chart. This leads to the use of manual commands to add theses annotations, as described [here](https://github.com/openfaas-incubator/openfaas-linkerd2#step-4-add-linkerd-2-to-openfaas) . This is bad for any GitOps flow.
It may also leads to problems when upgrading OpenFaaS with Helm.

## Expected Behaviour
A boolean value is added by the user in his configuration file, for example "linkerd2: true".
The necessary annotations are added to the deployments when helm install or helm upgrade is called.

## Current Behaviour
The user deploys OpenFaaS with helm, then has to launch 4 commands manually to add the annotations.

## Possible Solution
Modify the helm chart to optionally add theses annotations, or to give the possibility to add any annotation (in this case the value will not be a boolean but a dict).

## Context
Our goal is to have a 100% GitOps flow, with everything in git repositories.
We will use Flux + Helm to achieve that, but theses annotations are currently a blocker.

I'm willing to work on a PR if we agree that this is a valid use case.

**Comment by alexellis** [comment]
Hi @tlemarchand thanks for your interest in OpenFaaS. Which specific annotation are you asking for?

Could you tell us what you're using OpenFaaS for and what company this is for?

**Comment by tlemarchand** [comment]
Hi @alexellis , thank you for your quick answer !

To my knowledge, two annotations would be needed : 

- "linkerd.io/inject: enabled" on : 
   - deploy/gateway
   - deploy/basic-auth-plugin
   - deploy/faas-idler
   - deploy/queue-worker
- "config.linkerd.io/skip-outbound-ports: 4222" on : 
   - deploy/gateway
   - deploy/queue-worker

It's for AXA France, currently a POC project.
I think it would ease the deployment of a PLONK stack to be able to inject automatically theses annotations. I'll fork the repo to test theses changes, and if you think it can be useful to the upstream I'll do a PR.

**Comment by alexellis** [comment]
What are your thoughts on setting this on your namespace instead? It may not help with NATS, but should with the rest?

**Comment by tlemarchand** [comment]
It will probably work, I did not test it.
However it will be injected on all resources of the openfaas namespace, including resources not existing yet, which may lead to problems in the future ?
I would feel safer to add it only on resources needing it, but if you don't think it can be a problem, then why not !

**Comment by cpretzer** [comment]
@tlemarchand having worked with OpenFaaS and Linkerd a bit, I think it's safe to annotate the entire namespace.

Linkerd has [automatic protocol detection](https://linkerd.io/2/features/protocol-detection/), so if there are future components which have a protocol that Linkerd doesn't support, then it will not proxy those requests.

> I think it would ease the deployment of a PLONK stack to be able to inject automatically theses annotations. I'll fork the repo to test theses changes, and if you think it can be useful to the upstream I'll do a PR.

This sounds like a great PR, so please let us know how your tests go.

**Comment by stefanprodan** [comment]
We could add the annotations to the [namespaces.yml](https://github.com/openfaas/faas-netes/blob/master/namespaces.yml) the same way we did for Istio.

**Comment by tlemarchand** [comment]
> We could add the annotations to the [namespaces.yml](https://github.com/openfaas/faas-netes/blob/master/namespaces.yml) the same way we did for Istio.

I did just that, but I had to add another annotation for inbound port, since the NATS pods are also injected.
It works very well now.

```
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/skip-inbound-ports: "4222"
    config.linkerd.io/skip-outbound-ports: "4222"
  labels:
    role: openfaas-system
    access: openfaas-system
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas-fn
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/skip-inbound-ports: "4222"
    config.linkerd.io/skip-outbound-ports: "4222"
  labels:
    istio-injection: enabled
    role: openfaas-fn
```

So, we may not need a change in the helm chart after all, just a small change in namespaces.yaml and a change in the [documentation](https://github.com/openfaas-incubator/openfaas-linkerd2#step-4-add-linkerd-2-to-openfaas).
