### ISSUE TITLE
Allow custom annotations on the 'gateway' deployment

### ISSUE THREAD

**Issue by jeffreymlewis** [openfaas/faas-netes#601]
Allow setting custom annotations on the `gateway` deployment created by the helm chart.

## Expected Behaviour
Specifying the following in `values.yaml` would set custom annotations on the 'gateway' deployment.
```
gateway:
  annotations:
    prometheus.io.scrape: "true"
    prometheus.io.port: "8082"
    my.custom.annotation: "here"
```

## Current Behaviour
There's currently no way to set custom annotations on the gateway deployment.

## Possible Solution
The Ingress object allows setting custom annotations. We could just plagiarize that code.

## Context
I need to ingest 'gateway' metrics into Datadog, which requires setting annotations on the deployments creating the gateway pods. Other applications/situations will likely benefit from this enhancement as well.

## Your Environment
As of this writing (03/27/2020) I'm using faas-netes helm chart 0.10.1.
