### ISSUE TITLE
Question: GKE use-case

### ISSUE THREAD

**Issue by id0Sch** [openfaas/faas-netes#63]
## Current Behaviour
i used Helm to setup the openfaas stack
configured my function with
``` yaml
gateway: http://localhost:8001/api/v1/proxy/namespaces/default/services/gateway:8080
```
deployed it, but  when I navigate to `https://EXTERNAL_CLUSTER_IP/system/functions/FUNCTION_NAME`
I'm getting the following error
```
User "system:anonymous" cannot get path "/system/functions/FUNCTION_NAME".: "No policy matched.\nUnknown user \"system:anonymous\""
```

## Context
I'm trying to deploy a telegram bot that uses a webhook

I'm new to kubernetes and i've had a really hard time deploying to GKE, I think we can all benefit from some more resources regarding this combo (gke+faas-nets)

Thanks!

**Comment by alexellis** [comment]
You should not navigate to that endpoint, it's not valid or viewable in a web-browser.

Can you explain what you are trying to do?

**Comment by alexellis** [comment]
We've also had people deploy to GKE including @rawkode ... David please can you comment?

**Comment by id0Sch** [comment]
Wow that was fast! 🚀 

I'm trying to invoke the function.
Also, the gateway UI is not functional when using `kubectl proxy` on GKE
![image](https://user-images.githubusercontent.com/5864772/32039315-41ffa210-ba36-11e7-8531-46d6d8e184ce.png)

**Comment by id0Sch** [comment]
@rawkode , @alexellis Im also documenting the steps I used, maybe we can expand it to a GKE tutorial or something
https://gist.github.com/id0Sch/6f4d068032f9bd11f267301d1744ffdd

**Comment by alexellis** [comment]
I thought that GKE supported a LoadBalancer?

* Why is a proxy needed?
* Why do you need to push to the Google registry? Doesn't the Hub work on GKE?

Maybe using the helm chart would work better?

**Comment by id0Sch** [comment]
I'm deploying to the Google registry since its private (that part worked well).
not sure about the proxy, but it's the only way I got access to the dashboards (im new to kube.)

**Comment by rawkode** [comment]
Hi @id0Sch, hopefully I can help!

You've deployed using `Helm` I believe, which is great. I've then used `kubectl -n openfaas get pods` and `kubectl -n openfaas port-forward gateway-pod-name 8080:8080` and browsed to the UI on `http://localhost:8080`

Please replace your namespace with whatever you used and the pod name

You can also use this port-forward to work with the `faas-cli`

**Comment by rawkode** [comment]
If you wish to make your Gateway public, you'll need to add an ingress controller in front of the Gateway service.

**Comment by rawkode** [comment]
This is my Ingress resource:

```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: openfaas-gateway-ingress
  namespace: openfaas
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: removed
    http:
      paths:
        - backend:
            serviceName: gateway-external
            servicePort: 8080
```
