### ISSUE TITLE
Support for AWS IRSA

### ISSUE THREAD

**Issue by ghostsquad** [openfaas/faas-netes#660]
Is there a way to project values into the containers created by OpenFaas like I can with Kubernetes? Specifically, I'm interested in the following:

https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

```yaml
apiVersion: apps/v1
kind: Pod
metadata:
  name: myapp
spec:
  serviceAccountName: my-serviceaccount
  containers:
  - name: myapp
    image: myapp:1.2
    env:
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::123456789012:role/eksctl-irptest-addon-iamsa-default-my-serviceaccount-Role1-UCGG6NDYZ3UE
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    volumeMounts:
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token
        readOnly: true
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
```

So that I do not need to create a service account and manage aws access tokens.
