### ISSUE TITLE
Feature request: Expose Node IP within function container

### ISSUE THREAD

**Issue by andyy5** [openfaas/faas-netes#677]
## Expected Behaviour

I'm trying to send datadog traces from my function to my datadog agent.

For the function, I need to set the environment variable `DD_AGENT_HOST` to the node's IP, like this:

```
env:
- name: DD_AGENT_HOST
   valueFrom:
      fieldRef:
        fieldPath: status.hostIP
```

But based on the docs and code, it seems like this is not supported?

I'm wondering if there is any workaround that can help me here.

## Current Behaviour

Not implemented

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I'm trying to send datadog traces from my function to my datadog agent and need to set the function's environment variable `DD_AGENT_HOST` to the node's IP.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): latest

* Docker version `docker version` (e.g. Docker 17.0.05 ): latest

* What version and distriubtion of Kubernetes are you using? `kubectl version` latest

* Operating System and version (e.g. Linux, Windows, MacOS): linux, macos

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
/set title: Feature request: Expose Node IP within function container

**Comment by alexellis** [comment]
Thanks for your suggestion. This does seem like an edge-case, but would you like to spend some time looking into possible solutions and report back?

**Comment by andyy5** [comment]
@alexellis  some options:

- add a new field specifically for accessing pod info:

YAML
```
pod_info:
  my_env1: status.podIP
  my_env2: status.hostIP
  my_env3: spec.serviceAccountName
  my_env4: spec.nodeName
```

REST API
```
"podInfo": {
  "my_env1": "status.hostIP"
  ...
}
```

- use the existing field for environment variables, but openfaas needs to recognize certain env values:

YAML
```
environment:
  my_env: status.hostIP
```

REST API
```
"envVars": {
  "my_env": "status.hostIP"
}
```
