### ISSUE TITLE
Adding secrets that have overlapping keys causes an error

### ISSUE THREAD

**Issue by talzion12** [openfaas/faas-netes#693]
## Expected Behaviour
Using the faasnetes operator I created the following function (I replaced some real values with placeholders):
```yaml
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: my-function
spec:
  name: my-function
  handler: ls
  image: ubuntu:20.04
  labels:
    com.openfaas.scale.zero: "true"

  annotations:
    com.openfaas.health.http.path: '/health'
  
  environment:
    PASSWORD_1_PATH: /var/openfaas/secrets/password1
    PASSWORD_2_PATH: /var/openfaas/secrets/password2
  
  secrets:
  - password-1
  - password-2
```

I expect each secret to be mounted into a different directory so that overlapping keys don't cause an error.

## Current Behaviour
In this case the operator printed the following error:
```
Updating deployment for 'my-function' failed: Deployment.apps "my-function" is invalid: [spec.template.spec.volumes[0].projected: Invalid value: "password-2": conflicting duplicate paths, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "my-function-projected-secrets"]
```

## Possible Solution
I think each secret should be mounted into a different directory, although that is a breaking change.

Another option that doesn't break the current API is to allow to reference secrets/configmaps/other k8s references in the `environment` field like so:
```yaml
environment:
  PASSWORD_1:
    secretKeyRef:
      name: password
      key: password
```

I realize it might be less secure to pass secrets in env variables, but it's easier than passing a path. And it would be nice to be able to refer to configmaps and other k8s `EnvVarSource`s.

## Steps to Reproduce (for bugs)
* Deploy the above function along with the following secrets:
```yaml
apiVersion: v1
data:
  password: MTIz
kind: Secret
metadata:
  creationTimestamp: null
  name: password-1
---
apiVersion: v1
data:
  password: MTIz
kind: Secret
metadata:
  creationTimestamp: null
  name: password-2
```

* See the error in the operator's logs.

## Context
I'm trying to mount 2 secrets that share the same keys on Kubernetes.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
Not using faas-cli, just the operator

* Docker version `docker version` (e.g. Docker 17.0.05 ):
19.03.13-ce

* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"archive", BuildDate:"2020-09-18T18:46:38Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
Not sure, the default gke network driver
