### ISSUE TITLE
Support imagePullSecrets on Helm chart

### ISSUE THREAD

**Issue by efossas** [openfaas/faas-netes#702]
The helm chart does not support adding imagePullSecrets for pulling images from private repos. I would like to open a PR for this. Just making sure y'all are on board with this.

## Expected Behaviour
Be able to add imagePullSecrets in the values.yml file to pull images from private repos.

## Current Behaviour
not possible as far as  I can tell

## Possible Solution
add imagePullSecrets config to the helm templates

## Context
With DockerHub beginning to rate limit image pulls, I'm moving all of our images to our internal registry. Our internal registry is more performant and reliable anyways.

## Your Environment
latest chart version (6.1.1) on EKS

**Comment by alexellis** [comment]
Image pull secrets in openfaas will only cover what we installed into your cluster, but you'll need the pull secrets for every namespace including kube-system, default and any others like cert-manager.

Questions for you: how are you deploying OpenFaaS in production?

For development, have you considered using https://github.com/alexellis/registry-creds?

**Comment by efossas** [comment]
Right. I don't mind adding image pull secrets where needed. As of now, everything that needs them on our clusters is configured to use them through helm charts.

We don't use OpenFaaS in production yet. I'm exploring it as a scale to zero solution for our "serverless" workloads.

Your registry-creds project looks a lot like this one: [https://github.com/titansoft-pte-ltd/imagepullsecret-patcher](https://github.com/titansoft-pte-ltd/imagepullsecret-patcher)

That's very cool, though I generally try to limit the number of operators and CRDs we use as much as possible and I would prefer to avoid another tool.

**Comment by alexellis** [comment]
If you're using a GitOps approach to deploying applications - like Argo or Flux, I would suggest you encode the image pull secret as part of that workflow.

I'm not sure the OpenFaaS chart should be responsible for this request, but am willing to keep the issue around to see how popular the request is.

**Comment by alexellis** [comment]
For anyone landing here - this is how you can configure image pull secrets - https://docs.openfaas.com/deployment/kubernetes/#use-a-private-registry-with-kubernetes

**Comment by alexellis** [comment]
Eric, can you tell us what other alternative solutions you can see here?

**Comment by denstorti** [comment]
Hi Eric, I sorted this out by creating a new ServiceAccount with imagePullSecrets:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-openfaas-sample-sayhello
  namespace: openfaas-fn
imagePullSecrets:
- name: registry-creds
```

Then passing it with the annotation in the Function object:
```
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: openfaas-sample-sayhello
spec:
  annotations:
    com.openfaas.serviceaccount: sa-openfaas-sample-sayhello
  name: openfaas-sample-sayhello
  image: docker.repo.bendigobank.com.au/openfaas-sample-sayhello:1.0.0
```

I hope this helps.
