### ISSUE TITLE
Support request on timeout configuration

### ISSUE THREAD

**Issue by kevin-lindsay-1** [openfaas/faas-netes#729]
## Expected Behaviour

Setting `gateway.upstreamTimeout` should lower/raise the timeout.

## Current Behaviour

Setting `gateway.upstreamTimeout` does not lower/raise the timeout, however the environment variable appears to be coming through correctly. Based on my testing, this appears to be coming from the gateway.

## Possible Solution

I was looking through previous issues, and it looks like a timeout default was recently changed. Maybe there was a typo pulling a config key, or a value that was previously `8s` was not changed.

## Steps to Reproduce (for bugs)

1. Use helm to install `6.2.2` (only effects this version by my testing).
2. Set `gateway.upstreamTimeout`.
3. Make a function take longer than `8s`, receive error from the gateway operator's logs of
```
error with proxy request to: http://172.17.0.9:8080, Post http://172.17.0.9:8080: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
4. Use helm to uninstall, reinstall `6.2.1`, repeat steps, issue does not occur.

## Context

Breaks long-running functions. Rolling back to `6.2.1`.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): `0.12.9`

* Docker version `docker version` (e.g. Docker 17.0.05 ): `20.10.0`

* What version and distriubtion of Kubernetes are you using? `kubectl version`
I've tried this on `1.19.X` and `1.17.X` during troubleshooting.

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS `11.0.1`

* Link to your project or a code example to reproduce issue: Will provide upon request, but this should be fairly easy to reproduce.

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
Not sure, I think minikube handles these details under the hood.

**Comment by kevin-lindsay-1** [comment]
This issue should probably be owned in `openfaas/faas`, however I created the issue in this repo because I can reproduce with a particular helm version.

**Comment by alexellis** [comment]
/set title: Support request on timeout configuration

**Comment by alexellis** [comment]
Please walk through this tutorial to learn how and where to configure timeouts:

https://docs.openfaas.com/tutorials/expanded-timeouts/

Take note of the watchdog version and any settings in your workload that may need configuring differently.

Feel free to put up full instructions for repro, with a code example.

**Comment by kevin-lindsay-1** [comment]
I've done a little more digging, and this appears to be caused by the change `gateway.directFunctions: false` being set since `6.2.2`.

It may have something to do with the fact that I use the `operator` rather than `faasnetes`.

My config, with comments removed:
```yaml
# Default namespace for functions
functionNamespace: openfaas-fn

serviceType: LoadBalancer

createCRDs: true

generateBasicAuth: false

# image pull policy for openfaas components, can change to `IfNotPresent` in offline env
openfaasImagePullPolicy: IfNotPresent

## OSS components

gateway:
  readTimeout: 24h
  writeTimeout: 24h
  # Must be smaller than read/write_timeout
  upstreamTimeout: 24h
  directFunctions: true


faasnetes:
  readTimeout: 24h
  writeTimeout: 24h

# replaces faas-netes with openfaas-operator
operator:
  create: true

queueWorker:
  maxInflight: 100
  ackWait: 24h
```
