### ISSUE TITLE
Function CRD - unusual behaviour with constraints: [ ]

### ISSUE THREAD

**Issue by aslanpour** [openfaas/faas-netes#829]
I have generated a CRD type yaml file for my function to be able to create my function using kubectl. It is working perfectly, but in one case I see the function is constantly rescheduled every 300s. This case is when I set constraints as null like this: `constraints: []`, but this pattern `constraints:`  has no issue.
## Expected Behaviour

The function is expected to be scheduled once and not rescheduled every 300s.

## Current Behaviour

The function is re-scheduled every 300s.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds

Perhaps verifying constraints value and treating [] (i.e., zero length) as "" or null will be good.

I have to either comment `constraints: []`, set it as `constraints:`, or give it a value.
## Which Solution Do You Recommend?

I think I should work as normal with `constraints: []`.
## Steps to Reproduce (for bugs)

1. Function CRD:
```
---
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: test
  namespace: openfaas-fn
spec:
  name: test
  image: aslanpour/irrigation:latest
  environment:
    REDIS_SERVER_IP: 10.43.242.161
    REDIS_SERVER_PORT: "3679"
    exec_timeout: 10s
    handler_wait_duration: 10s
    read_timeout: 10s
    write_debug: "true"
    write_timeout: 10s
  labels:
    com.openfaas.scale.max: "1"
    com.openfaas.scale.min: "1"
    com.openfaas.scale.zero: "true"
  annotations:
    linkerd.io/inject: disabled
  limits:
    memory: ""
    cpu: 280m
  requests:
    memory: ""
    cpu: 140m
  constraints: []
```
2. command to deploy: 
3. kubectl create -f test.crd.yaml
4. Function is deployed
5. Right after deployment: kubectl get function -n openfaas-fn
```test-6477fc76cc-srcxj              1/1     Running   0          3s   10.42.0.47    master   <none>           <none>```
6. After around 5 minutes and 15sec after deployment: kubectl get function -n openfaas-fn
```test-6477fc76cc-srcxj              1/1     Running   0          15s   10.42.0.47    master   <none>           <none> ```
7. kubectl describe function/test -n openfaas-fn
```
Name:         test
Namespace:    openfaas-fn
Labels:       <none>
Annotations:  <none>
API Version:  openfaas.com/v1
Kind:         Function
Metadata:
  Creation Timestamp:  2021-08-18T23:57:41Z
  Generation:          1
  Managed Fields:
    API Version:  openfaas.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:annotations:
          .:
          f:linkerd.io/inject:
        f:constraints:
        f:environment:
          .:
          f:REDIS_SERVER_IP:
          f:REDIS_SERVER_PORT:
          f:exec_timeout:
          f:handler_wait_duration:
          f:read_timeout:
          f:write_debug:
          f:write_timeout:
        f:image:
        f:labels:
          .:
          f:com.openfaas.scale.max:
          f:com.openfaas.scale.min:
          f:com.openfaas.scale.zero:
        f:limits:
          .:
          f:cpu:
          f:memory:
        f:name:
        f:requests:
          .:
          f:cpu:
          f:memory:
    Manager:         kubectl-create
    Operation:       Update
    Time:            2021-08-18T23:57:41Z
  Resource Version:  3286655
  UID:               ead1826a-479c-43d4-be2e-4ae5b2ab571e
Spec:
  Annotations:
    linkerd.io/inject:  disabled
  Constraints:
  Environment:
    REDIS_SERVER_IP:        10.43.242.161
    REDIS_SERVER_PORT:      3679
    exec_timeout:           10s
    handler_wait_duration:  10s
    read_timeout:           10s
    write_debug:            true
    write_timeout:          10s
  Image:                    aslanpour/irrigation:latest
  Labels:
    com.openfaas.scale.max:   1
    com.openfaas.scale.min:   1
    com.openfaas.scale.zero:  true
  Limits:
    Cpu:     280m
    Memory:
  Name:      test
  Requests:
    Cpu:     140m
    Memory:
Events:
  Type    Reason  Age                    From               Message
  ----    ------  ----                   ----               -------
  Normal  Synced  3m41s (x2 over 5m47s)  openfaas-operator  Function synced successfully
  Normal  Synced  3m40s                  openfaas-operator  Function synced successfully
```
## Context

This is rescheduling the function unwantedly.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
 ```
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  72816d486cf76c3089b915dfb0b66b85cf096634
 version: 0.13.13
* Docker version `docker version` (e.g. Docker 17.0.05 ):
20.10.7
```
* What version and distriubtion of Kubernetes are you using? `kubectl version`
K3s
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:54:11Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm"}
```
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux and ARM arch.
* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
