### ISSUE TITLE
[Question] Is it possible to expose k8s pod information to deployed functions?

### ISSUE THREAD

**Issue by vojtechtoman** [openfaas/faas-netes#848]
## Expected Behaviour
I work at [BRYTER](http://bryter.io) where we use OpenFaaS as part of our integrations platform (3rd-party integrations are operated as OpenFaaS functions). We are using [Datadog APM](https://www.datadoghq.com/product/apm/) for distributed tracing and application monitoring in our product and we would like to enable the same for our (OpenFaaS-based) integrations. The Datadog [documentation](https://docs.datadoghq.com/agent/kubernetes/apm/?tab=helm) suggests that we need to 'configure application pods to pull the host IP in order to communicate with the Datadog Agent', namely point the `DD_AGENT_HOST` environment variable to `status.hostIP`, like in the following example:

```yaml
apiVersion: apps/v1
kind: Deployment
 # ...
    spec:
      containers:
      - name: "<CONTAINER_NAME>"
        image: "<CONTAINER_IMAGE>"/"<TAG>"
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
```
Is there a way, at function deploy time, to achieve something similar to the above?

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Context
See the description above.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distribution of Kubernetes are you using? `kubectl version`: v1.21.2-eks-0389ca3, faas-netes 0.13.5, faas 0.21.1

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by vojtechtoman** [comment]
@alexellis my apologies, I have updated the issue to use the template.

**Comment by vojtechtoman** [comment]
In our specific case, we want to enable [Datadog tracing](https://docs.datadoghq.com/tracing/setup_overview/setup/java) for the deployed functions. The challenge is that for that to work, we need to set the `DD_AGENT_HOST` environment variable on the deployment so that it points to the node IP provided by K8s. As far as I can tell, there is no way to pass an equivalent of:

```yaml
  env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
```

when deploying the function via the `/system/functions` endpoint - or is there? That's what my question is about - or if there is another way of accessing `status.hostIP` on the deployment level.
