### ISSUE TITLE
[Feature request] Topology Spread Constraints & Per-Deployment Affinity

### ISSUE THREAD

**Issue by kevin-lindsay-1** [openfaas/faas-netes#856]
It's fairly normal for k8s deployments that live in a multi-zone cluster to have topology constraints or affinity rules, however it's fairly normal to have an affinity rule per deployment, as the label selectors for pods are typically different per-deployment.

## Expected Behaviour

Be able to set anti-affinity and topology spread constraints per deployment.

## Current Behaviour

Cannot set affinity per deployment, and topology spread constraints are not in the chart.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ ] No
- [x] No, but I sponsor Alex

## List All Possible Solutions and Workarounds

Affinity is currently a global option for what appears to be all deployments. Per-deployment overrides is a reasonable option.

Topology Spread Constraints are not currently in the chart, and I don't think a global configuration option would really even work, as the `labelSelector` would need to be different per-deployment.

## Which Solution Do You Recommend?

Make overrides for affinity and make topology spread configurable, not implementing a global variant.

## Context

Trying to have HA for `faas-netes/openfaas`.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.13.13

* Docker version `docker version` (e.g. Docker 17.0.05 ):
20.10.8

* What version and distriubtion of Kubernetes are you using? `kubectl version`
server v1.21.3
client v1.22.2

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by kevin-lindsay-1** [comment]
Maybe a cluster would solve for both NATS high availability and this shared state? Assuming you could mount a file via a PVC and let RAFT take care of the rest, might allow for multiple NATS pods at once, and be persistent, killing two birds with one stone.

A SQL database running in k8s would probably have the same issue, meaning I'd either have to set up an external k8s database, or it would need some kind of k8s-level persistence.

**Comment by kevin-lindsay-1** [comment]
> PVC and cluster sounds simpler, though.

That said, using AWS in a (potentially) multi-regional, multi-zonal, multi-nodal spread, EFS or FSx are probably the best choices, as both appear to support multi-zone/region use cases.

People installing a NATS cluster using a PVC with multi-zonal persistence will likely need something similar, which is potentially an extra wrench to throw in, but we would probably be able to handle the persistence just fine with EFS; people say "it's kinda slow" at lower workloads, but I don't think that's necessarily a big deal for something like a queue.

**Comment by alexellis** [comment]
Kevin mentioned that this became more important since his team moved to using spot instances. I know that other openfaas users make use of spot instances, or GKE's preemptive VMs.

The spread or affinity rule would schedule the three replicas of the gateway onto three separate nodes before adding duplicate replicas to the same hosts again, so that if a VM is reclaimed by the cloud provider, there are other replicas available to serve requests whilst a new host is provisioned.

> Affinity is currently a global option for what appears to be all deployments. Per-deployment overrides is a reasonable option.

So, is there a way we can achieve this result without making the chart much more verbose and complex to manage? i.e. with a single rule that templates the deployment labels etc into the right place?

https://github.com/openfaas/faas-netes/issues/856#issuecomment-948798734

**Comment by kevin-lindsay-1** [comment]
> is there a way we can achieve this result without making the chart much more verbose and complex to manage?
I do not currently have a need for overrides if the label selectors were automatically added per deployment.

I would also consider a default affinity rule for services to `preferDuringSchedulingIgnoredDuringExecution` nodes with other OF components on them, a la:
```yaml
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: app
            operator: In
            values:
            - openfaas
```
This rule basically says "I prefer to be on a node with openfaas components".

**Comment by alexellis** [comment]
> I do not currently have a need for overrides if the label selectors were automatically added per deployment.

I can see labels, so could you help me understand which labels are not being added? Perhaps you could show an example of what you got and what you expected?

`kubectl get deploy -n openfaas gateway -o yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: openfaas
    meta.helm.sh/release-namespace: openfaas
  creationTimestamp: "2021-11-01T17:50:20Z"
  generation: 1
  labels:
    app: openfaas
    app.kubernetes.io/managed-by: Helm
    chart: openfaas-8.1.3
    component: gateway
    heritage: Helm
    release: openfaas


spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8082"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: gateway
```

I can see `app: gateway` at each level. Which additional labels are needed at the pod level?

**Comment by kevin-lindsay-1** [comment]
@alexellis I'm referring to what @LucasRoesler was thinking on https://github.com/openfaas/faas-netes/issues/856#issuecomment-948798734. Effectively, the chart could have a global and not have the need for an override if each component's affinity/tsc rules templated in their rules.

For example:
- with pod topology spread constraints, I could see the pod's `component` label being used to identify which component is being spread.
- with affinity rules, I could see pods having a default rule of __preferring__ to be scheduled on the same node as other openfaas components, via the `app` label.

**Comment by alexellis** [comment]
Given the amount of conversation it's taking to understand the problem, I think your original suggestion may fit better of having one of these per every deployment in the chart. It will default to off, but can be enabled if required.

values.yaml will have your overrides for images and configuration

```yaml
gateway:
  image: ghcr.io/openfaas/gateway:latest
```

values-topology.yaml, would look like this:

```yaml

gateway:
  affinity: {...} # [proposed] overrides global
  topologySpreadConstraints: # [proposed] overrides global
    - ...
      labelSelector:
        app: gateway
    - ...
      labelSelector:
        app: gateway

faasIdler:
  affinity: {...} # [proposed] overrides global
  topologySpreadConstraints: # [proposed] overrides global
    - ...
      labelSelector:
        app: faas-idler
    - ...
      labelSelector:
        app: faas-idler
```

To make this happen, do we just need to output whatever is put into the chart into the deployment and quote it, or are any additional more complex templating rules needed for dynamic fields?
