### ISSUE TITLE
Differenciate from liveness probe and readiness probe

### ISSUE THREAD

**Issue by jastabile** [openfaas/faas-netes#859]
## My actions before raising this issue
- [X] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X] Read/searched [the docs](https://docs.openfaas.com/)
- [X] Searched [past issues](/issues)

When I use the annotation ```com.openfaas.health.http.path``` to define a custom path for health checks, it changes both liveness and readiness probe to that path.

## Expected Behaviour
Possibility to have more annotations to achieve liveness and readiness probe separately.

## Current Behaviour
There is no annotation to treat liveness and readiness as different paths?

## Are you a GitHub Sponsor (Yes/No?)
No

Check at: https://github.com/sponsors/openfaas
- [x] Yes
- [ ] No

**Comment by alexellis** [comment]
@jastabile we haven't heard from you in two weeks, would you like me to close this issue?

Ideally, we'd like to hear from you what you tried that didn't work as a result of this, and a repo that we can deploy to see the problem for ourselves.

Cheers,

Alex

**Comment by jastabile** [comment]
@alexellis hello, thanks for your response. I think it would be easy for understand.

I will try to explain it with this example, let's say we hace this yaml file for the function definition:
```
version: 1.0
provider:
  name: openfaas
  gateway: http://gateway
functions:
  function1:
    lang: node14
    handler: ./app
    image: busybox
    secrets:
    - regcred
    annotations:
      com.openfaas.health.http.path: /ready
    requests:
      memory: "4000Mi"
    environment:
      env1: "env1"
```

This will create a deployment that will have something like this in the readiness and liveness probe block:
```
livenessProbe:
  httpGet:
    path: /ready
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 2
  timeoutSeconds: 1
  periodSeconds: 2
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /ready
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 2
  successThreshold: 1
  failureThreshold: 3
```

But what about if I want to have two different routes for each liveness and readiness (i.e: /live and /ready respectively)?
Is there a `com.openfaas.live.http.path` and `com.openfaas.ready.http.path` annotation?
