### ISSUE TITLE
faas-cli logs not showing

### ISSUE THREAD

**Issue by lapwat** [openfaas/faas-netes#912]
## Expected Behaviour

I would expect to see the text printed to stdout/stderr by my function in the function logs.

## Current Behaviour

Text written on stdout/sterr are not showing in the function logs of the function.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Steps to Reproduce (for bugs)

1. Install Openfaas Helm chart on Kubernetes
2. Write a golang function that logs a message

```go
package function

import (
	"fmt"
	"log"
)

// Handle a serverless request
func Handle(req []byte) string {
	log.Println("Please print my logs")
	return fmt.Sprintf("Hello, Go. You said: %s", string(req))
}
```

3. Deploy the function
3. Invoke the function on the Web UI
4. Check the logs of the function

```sh
k logs test-log-go-xxx-xxx
2022/02/10 13:32:56 Version: 0.2.0	SHA: 56bf6aac54deb3863a690f5fc03a2a38e7d9e6ef
2022/02/10 13:32:56 Timeouts: read: 5s write: 5s hard: 0s health: 5s.
2022/02/10 13:32:56 Listening on port: 8080
2022/02/10 13:32:56 Writing lock-file to: /tmp/.lock
2022/02/10 13:32:56 Metrics listening on port: 8081
2022/02/10 13:33:00 Forking fprocess.
2022/02/10 13:33:00 Wrote 64 Bytes - Duration: 0.004976s
```

## Context

If I execute the function locally (go run main.go), the logs are showing in my terminal as expected.

Not sure if it is a Kubernetes, OpenFaas or watchdog issue.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.13.13
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)? Kubernetes server v1.23.1

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

**Comment by LucasRoesler** [comment]
@lapwat I think this is an issue with your template choice. The original watchdog captures the function logs as the response. This means you won't see logs in kubernetes or the faas-cli (which is powered by the k8s logs). 

I generally recommend using the new templates like golang-http. This uses the newer `of-watchdog` which does use the function output as a response, instead using http. This means your print statement would behave as normal.

Alternatively, if you really want to stay with the original template, then there is an env variable you can set so that stderr is _not_ captured by the watchdog.  Set `combine_output: "false"` in your stack.yaml for the function and then in your Go code you need to change the log output

```go
log.SetOutput(os.Stderr)
```

**Comment by lapwat** [comment]
Hi thanks for the tips, I am indeed using the `go` template, I will give a "go" to the `golang-http` template. Thanks

**Comment by lapwat** [comment]
@LucasRoesler I used golang-middleware and the logs are showing in Kubernetes logs which is great. I would like to see them in Loki source on Grafana but they are not showing with this query: `{faas_function="test-log"}`

Do you have any clue ?

# Handler

```go
package function

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
)

func Handle(w http.ResponseWriter, r *http.Request) {
	var input []byte

	if r.Body != nil {
		defer r.Body.Close()

		body, _ := ioutil.ReadAll(r.Body)

		input = body
	}

	log.Println("this is a logged line")
	log.Printf("this is a logged line formatted with: %s", "tit")

	w.WriteHeader(http.StatusOK)
	w.Write([]byte(fmt.Sprintf("Body: %s", string(input))))
}
```

**Comment by lapwat** [comment]
1. I used FluxCD to deploy my cluster following gitops principles

Here are the different helm releases. Note that I have changed openfaas function namespace.

# Openfaas

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: serverless
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://openfaas.github.io/faas-netes/
      chart: openfaas
      version: 10.0.8
      sourceRef:
        kind: HelmRepository
        name: openfaas
        namespace: flux-system
  values:
    functionNamespace: serverless-fn
    generateBasicAuth: true
    ingress:
      enabled: true
      hosts:
        - host: xxx
          serviceName: gateway
          servicePort: 8080
          path: /
      tls:
        - hosts:
          - xxx
          secretName: certificate-domain
    gateway:
      readTimeout: 1h10m
      writeTimeout: 1h10m
      upstreamTimeout: 1h  # Must be smaller than read/write_timeout
    queueWorker:
      replicas: 5
      ackWait: 1h
```

# Loki stack

```yml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: serverless
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki-stack
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    grafana:
      enabled: true
```

Loki source is detected on grafana. "fork" logs are showing when querying Loki.

```
  |   | 2022-02-14T15:13:22.52852706Z stderr F 2022/02/14 15:13:22 Exiting. Active connections: 0
  |   | 2022-02-14T15:13:22.527152672Z stderr F 2022/02/14 15:13:22 No new connections allowed, draining: 0 requests
  |   | 2022-02-14T15:13:17.525698759Z stderr F 2022/02/14 15:13:17 Removing lock-file : /tmp/.lock
  |   | 2022-02-14T15:13:17.525609741Z stderr F 2022/02/14 15:13:17 SIGTERM: no new connections in 5s
  |   | 2022-02-10T13:28:09.67862275Z stderr F 2022/02/10 13:28:09 Wrote 23 Bytes - Duration: 0.100181s
  |   | 2022-02-10T13:28:09.578412011Z stderr F 2022/02/10 13:28:09 Forking fprocess.
  |   | 2022-02-10T13:11:49.682401932Z stderr F 2022/02/10 13:11:49 Wrote 23 Bytes - Duration: 0.103041s
  |   | 2022-02-10T13:11:49.579291166Z stderr F 2022/02/10 13:11:49 Forking fprocess.
  |   | 2022-02-10T13:11:49.344198477Z stderr F 2022/02/10 13:11:49 Wrote 23 Bytes - Duration: 0.091141s
  |   | 2022-02-10T13:11:49.253006487Z stderr F 2022/02/10 13:11:49 Forking fprocess.
  |   | 2022-02-10T13:11:48.476240608Z stderr F 2022/02/10 13:11:48 Wrote 23 Bytes - Duration: 0.113023s
  |   | 2022-02-10T13:11:48.362962799Z stderr F 2022/02/10 13:11:48 Forking fprocess.
  |   | 2022-02-10T13:11:48.052734789Z stderr F 2022/02/10 13:11:48 Wrote 23 Bytes - Duration: 0.106354s
  |   | 2022-02-10T13:11:47.945892485Z stderr F 2022/02/10 13:11:47 Forking fprocess.
  |   | 2022-02-10T13:11:45.418488825Z stderr F 2022/02/10 13:11:45 Metrics listening on port: 8081
  |   | 2022-02-10T13:11:45.418428953Z stderr F 2022/02/10 13:11:45 Writing lock-file to: /tmp/.lock
  |   | 2022-02-10T13:11:45.418423232Z stderr F 2022/02/10 13:11:45 Listening on port: 8080
  |   | 2022-02-10T13:11:45.418410258Z stderr F 2022/02/10 13:11:45 Timeouts: read: 5s write: 5s hard: 0s health: 5s.
  |   | 2022-02-10T13:11:45.417971911Z stderr F 2022/02/10 13:11:45 Version: 0.2.0	SHA: 56bf6aac54deb3863a690f5fc03a2a38e7d9e6ef
  |   | 2022-02-10T13:08:13.444609954Z stderr F 2022/02/10 13:08:13 Exiting. Active connections: 0
  |   | 2022-02-10T13:08:13.442827657Z stderr F 2022/02/10 13:08:13 No new connections allowed, draining: 0 requests
  |   | 2022-02-10T13:08:08.441283471Z stderr F 2022/02/10 13:08:08 Removing lock-file : /tmp/.lock
  |   | 2022-02-10T13:08:08.441197078Z stderr F 2022/02/10 13:08:08 SIGTERM: no new connections in 5s
  |   | 2022-02-10T13:05:54.072056277Z stderr F 2022/02/10 13:05:54 Wrote 18 Bytes - Duration: 0.095216s
  |   | 2022-02-10T13:05:53.978975934Z stderr F 2022/02/10 13:05:53 Forking fprocess.
  |   | 2022-02-10T13:05:12.165757595Z stderr F 2022/02/10 13:05:12 Metrics listening on port: 8081
  |   | 2022-02-10T13:05:12.165751374Z stderr F 2022/02/10 13:05:12 Writing lock-file to: /tmp/.lock
  |   | 2022-02-10T13:05:12.16574414Z stderr F 2022/02/10 13:05:12 Listening on port: 8080
  |   | 2022-02-10T13:05:12.165735564Z stderr F 2022/02/10 13:05:12 Timeouts: read: 5s write: 5s hard: 0s health: 5s.
  |   | 2022-02-10T13:05:12.165676854Z stderr F 2022/02/10 13:05:12 Version: 0.2.0	SHA: 56bf6aac54deb3863a690f5fc03a2a38e7d9e6ef
```

Thank you
