### ISSUE TITLE
Function CRD environment variables do not support valueFrom

### ISSUE THREAD

**Issue by kevin-lindsay-1** [openfaas/faas-netes#913]
The function CRD has a flatmap of strings for environment variables, but for certain things like needing the host IP, you need to use `valueFrom`, not just `value`.

## Expected Behaviour

You should be able to set environment variables that can use `valueFrom`, like any other pod.

## Current Behaviour

You can't use it.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [x] Yes
- [ ] No

## List All Possible Solutions and Workarounds

Either change the existing API to support `valueFrom`, or make a new `environmentFrom` which looks something like:
```yaml
# usage
environmentFrom:
  DD_AGENT_HOST:
    fieldRef:
      fieldPath: status.hostIP
```
```yaml
# deployment template
...
env:
{{- range $key, $value := .environment }}
- name: {{ $key }}
  value: {{ $value }}
{{- end }}
{{- range $key, $valueFrom := .environmentFrom }}
- name: {{ $key }}
  valueFrom: {{ toYaml $valueFrom | nindent 4 }}
{{- end }}
```

Alternatively, you could just bake this environment variable in by default (with a different name, obviously). Seems brittle though.

## Which Solution Do You Recommend?

I don't use the environment variable references like this very often, and I mostly just care that it works.

## Context

Trying to tell my datadog tracer & profiler on my function pod where the datadog agent lives, and can't easily because OF does not support the use case with their CRD.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
