### ISSUE TITLE
Constant Errors from Prometheus with clusterRole: false

### ISSUE THREAD

**Issue by kevin-lindsay-1** [openfaas/faas-netes#920]
If you don't have `clusterRole: true` in the OpenFaaS helm chart, prometheus produces massive amounts of error logs.

## Expected Behaviour

I would expect these background queries to not be constantly failing; I'm not exactly sure what's failing, as these logs appear to only be being generated from prometheus, and not other components in an upstream relationship.

## Current Behaviour

Error logs are being produced roughly once per second, complaining about the lack of permissions of the `openfaas-prometheus` role.

```
level=error ts=2022-02-22T16:25:05.487Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:335: Failed to list *v1.Node: nodes is forbidden: User \"system:serviceaccount:openfaas:openfaas-prometheus\" cannot list resource \"nodes\" in API group \"\" at the cluster scope"
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [x] Yes
- [ ] No

## List All Possible Solutions and Workarounds

Seems to me like the offending permission needs to be added to the `role` and not just the `clusterRole`, as this issue appears to be resolved by using the clusterRole.

Alternatively, clusterRole should be turned on if necessary, but the documented rationale for turning on that option does not apply for my use cases.

## Which Solution Do You Recommend?

Adding the necessary permissions to the prometheus role.

## Steps to Reproduce (for bugs)

Based on what I can see, this appears to be caused by using prometheus at all right now without the clusterRole enabled; seems like a query was added to it in some way that increased its needed permission scope, but the permission was not added to the role.

## Context

It's creating lots of logs, and showing up as errors, both creating log spam and saying there's a problem where there may not be any.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by kevin-lindsay-1** [comment]
The clusterRole has these permissions:
```yaml
rules:
- apiGroups: [""]
  resources:
    - services
    - endpoints
    - pods
    - nodes
    - nodes/proxy
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
```

Whereas the normal `role` has these permissions:
```yaml
rules:
- apiGroups: [""]
  resources:
    - services
    - endpoints
    - pods
  verbs: ["get", "list", "watch"]
```

At a minimum, it looks like a chart patch is needed for get operations on `nodes`.
