### ISSUE TITLE
Feature: Offer native Horizontal Pod Autoscaling as an alternative to alert-manager auto-scaling

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#99]
We should offer Horizontal Pod Autoscaling as an alternative to alert-manager+Prometheus auto-scaling for Kubernetes.

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

cc/ @stefanprodan 

### Solution

Auto-scaling currently works through the API Gateway so is automatic for any provider and can be tweaked with min/max scaling numbers and also varying alerts - if you want you can include NodeExporter metrics.

Built-in
Agnostic to provider

## HPA2 pros/cons

HPA2 is Kubernetes native
Will not work for Swarm or other back-ends
Harder to configure up front

A feature flag or / env-var would allow us to toggle.

**Comment by zouyee** [comment]
using metrics api or custom metrics to explore hpa？

**Comment by stefanprodan** [comment]
I would say we should try first to setup HPA based on requests/s

**Comment by ericstoekl** [comment]
Derek add label: revisit

**Comment by salekd** [comment]
Indeed, it would be nice to have this functionality in place. The alert-manager seems to check the number of the function calls per second. However, if a function runs longer than a second, the autoscaling will never trigger because there will always be only one execution per second.

HPA solve this by autoscaling based on for example CPU utilisation. I managed to setup HPA in the followings way:
1) Deploy function with `faas-cli`
2) Put HPA in place by `kubectl apply` on the following file

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: inception
  namespace: openfaas-fn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inception
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
```

3) Modify the deployment of the function `kubectl edit deployment inception -n openfaas-fn` by adding the lines below

```
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
```

It would be nice if we could do all this by specifying HPA in the function YAML file and using just faas-cli to deploy functions without the additional steps I described above.
